#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import re
import tempfile
import shutil

import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render offline joint trajectory with MuJoCo.")
    parser.add_argument("--urdf_path", type=str, required=True, help="URDF model path.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--trajectory_npz",
        type=str,
        default=None,
        help="Single selected_trajectory.npz generated by run_offline_validation.py",
    )
    group.add_argument(
        "--validation_dir",
        type=str,
        default=None,
        help="Validation output directory. Batch-process all */selected_trajectory.npz under it.",
    )
    parser.add_argument(
        "--output_mp4",
        type=str,
        default=None,
        help="Output mp4 path for single-file mode. Default: <npz_dir>/trajectory_best.mp4",
    )
    parser.add_argument(
        "--batch_output_name",
        type=str,
        default="trajectory_best.mp4",
        help="Output filename per demo folder in batch mode.",
    )
    parser.add_argument("--fps", type=int, default=30, help="Render fps.")
    parser.add_argument("--width", type=int, default=1280, help="Frame width.")
    parser.add_argument("--height", type=int, default=720, help="Frame height.")
    parser.add_argument("--stride", type=int, default=1, help="Render every N-th frame.")
    return parser.parse_args()


def _rewrite_urdf_package_paths(urdf_path: Path) -> Path:
    """
    Rewrite package:// URIs in URDF to absolute paths for MuJoCo.

    Example:
    package://rm_65_description/meshes/Link1.STL
      -> /abs/.../rm_65_description/meshes/Link1.STL
    """
    urdf_path = urdf_path.expanduser().resolve()
    text = urdf_path.read_text(encoding="utf-8")

    package_root = urdf_path.parent.parent  # .../rm_65_description
    package_name = package_root.name
    workspace_root = package_root.parent

    tmp_dir = Path(tempfile.mkdtemp(prefix="mujoco_rm65_"))
    tmp_urdf = tmp_dir / "model.urdf"

    mesh_ref_pat = re.compile(r'filename="([^"]+)"')
    matches = list(mesh_ref_pat.finditer(text))
    new_text = text
    offset = 0

    def _resolve_source(raw_ref: str) -> Path | None:
        if raw_ref.startswith("package://"):
            rest = raw_ref[len("package://") :]
            if "/" not in rest:
                return None
            pkg, rel = rest.split("/", 1)
            if pkg == package_name:
                cand = package_root / rel
            else:
                cand = workspace_root / pkg / rel
            return cand if cand.is_file() else None
        p = Path(raw_ref)
        if p.is_absolute():
            return p if p.is_file() else None
        # relative to urdf file
        cand = urdf_path.parent / p
        return cand if cand.is_file() else None

    copied_names: set[str] = set()
    for m in matches:
        raw_ref = m.group(1)
        src = _resolve_source(raw_ref)
        if src is None:
            continue
        basename = src.name
        dst = tmp_dir / basename
        if basename not in copied_names:
            shutil.copy2(src, dst)
            copied_names.add(basename)
        # Some MuJoCo URDF parsers only show/load basename; keep it simple and local.
        start, end = m.span(1)
        start += offset
        end += offset
        new_text = new_text[:start] + basename + new_text[end:]
        offset += len(basename) - (end - start)

    # As fallback, keep package URI rewriting too (for refs we didn't touch).
    replacement = package_root.as_posix().rstrip("/") + "/"
    new_text = new_text.replace(f"package://{package_name}/", replacement)

    def _generic_replace(match: re.Match[str]) -> str:
        pkg = match.group(1)
        cand = workspace_root / pkg
        if cand.is_dir():
            return cand.as_posix().rstrip("/") + "/"
        return match.group(0)

    new_text = re.sub(r"package://([^/]+)/", _generic_replace, new_text)

    tmp_urdf.write_text(new_text, encoding="utf-8")
    return tmp_urdf


def _load_q_traj(npz_path: Path) -> np.ndarray:
    data = np.load(npz_path, allow_pickle=False)
    if "q_selected" not in data:
        raise KeyError(f"{npz_path} missing key `q_selected`")
    q_traj = np.asarray(data["q_selected"], dtype=np.float64)
    if q_traj.ndim != 2:
        raise ValueError(f"q_selected must be (N,D), got {q_traj.shape} in {npz_path}")
    return q_traj


def _prepare_model(mujoco, urdf_path: Path, req_w: int, req_h: int):
    rewritten_urdf = _rewrite_urdf_package_paths(urdf_path)
    print(f"[INFO] rewritten URDF for MuJoCo: {rewritten_urdf}", flush=True)
    model = mujoco.MjModel.from_xml_path(str(rewritten_urdf))

    # MuJoCo offscreen framebuffer defaults are often 640x480.
    off_w = int(getattr(model.vis.global_, "offwidth", 640))
    off_h = int(getattr(model.vis.global_, "offheight", 480))
    render_w = min(int(req_w), off_w)
    render_h = min(int(req_h), off_h)
    if render_w != int(req_w) or render_h != int(req_h):
        print(
            f"[WARN] requested {req_w}x{req_h} exceeds offscreen "
            f"{off_w}x{off_h}, fallback to {render_w}x{render_h}",
            flush=True,
        )
    return model, render_w, render_h


def _render_one(
    mujoco,
    imageio,
    model,
    render_w: int,
    render_h: int,
    q_traj: np.ndarray,
    out_path: Path,
    fps: int,
    stride: int,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    mj_data = mujoco.MjData(model)
    renderer = mujoco.Renderer(model, width=render_w, height=render_h)

    nq_model = int(model.nq)
    nq_traj = int(q_traj.shape[1])
    nq_use = min(nq_model, nq_traj)
    if nq_use <= 0:
        renderer.close()
        raise RuntimeError(f"Invalid nq_use={nq_use}, model.nq={nq_model}, traj.nq={nq_traj}")

    writer = imageio.get_writer(str(out_path), fps=fps, codec="libx264", quality=8)
    try:
        for i in range(0, q_traj.shape[0], max(1, int(stride))):
            mj_data.qpos[:nq_use] = q_traj[i, :nq_use]
            mujoco.mj_forward(model, mj_data)
            renderer.update_scene(mj_data)
            frame = renderer.render()
            writer.append_data(frame)
    finally:
        writer.close()
        renderer.close()


def main() -> None:
    args = parse_args()
    try:
        import mujoco
    except ModuleNotFoundError as e:
        raise RuntimeError(
            "MuJoCo python package missing. Install with: pip install mujoco"
        ) from e

    try:
        import imageio.v2 as imageio
    except ModuleNotFoundError as e:
        raise RuntimeError(
            "imageio missing. Install with: pip install imageio imageio-ffmpeg"
        ) from e

    urdf_path = Path(args.urdf_path).expanduser().resolve()
    if not urdf_path.is_file():
        raise FileNotFoundError(f"URDF not found: {urdf_path}")
    model, render_w, render_h = _prepare_model(
        mujoco=mujoco, urdf_path=urdf_path, req_w=int(args.width), req_h=int(args.height)
    )

    if args.trajectory_npz is not None:
        traj_path = Path(args.trajectory_npz).expanduser().resolve()
        if not traj_path.is_file():
            raise FileNotFoundError(f"trajectory npz not found: {traj_path}")
        out_path = (
            Path(args.output_mp4).expanduser().resolve()
            if args.output_mp4
            else traj_path.parent / "trajectory_best.mp4"
        )
        q_traj = _load_q_traj(traj_path)
        print(
            f"[SINGLE] rendering {traj_path} -> {out_path} (frames={q_traj.shape[0]}, dof={q_traj.shape[1]})",
            flush=True,
        )
        _render_one(
            mujoco=mujoco,
            imageio=imageio,
            model=model,
            render_w=render_w,
            render_h=render_h,
            q_traj=q_traj,
            out_path=out_path,
            fps=int(args.fps),
            stride=int(args.stride),
        )
        print(f"[DONE] replay video: {out_path}", flush=True)
        return

    validation_dir = Path(args.validation_dir).expanduser().resolve()
    if not validation_dir.is_dir():
        raise FileNotFoundError(f"validation_dir not found: {validation_dir}")
    npz_paths = sorted(validation_dir.rglob("selected_trajectory.npz"))
    if len(npz_paths) == 0:
        raise RuntimeError(f"No selected_trajectory.npz found under: {validation_dir}")

    print(f"[BATCH] found {len(npz_paths)} trajectory files under {validation_dir}", flush=True)
    ok = 0
    fail = 0
    for i, traj_path in enumerate(npz_paths, start=1):
        out_path = traj_path.parent / str(args.batch_output_name)
        try:
            q_traj = _load_q_traj(traj_path)
            print(
                f"[BATCH {i}/{len(npz_paths)}] {traj_path.parent.name}: "
                f"frames={q_traj.shape[0]} dof={q_traj.shape[1]} -> {out_path.name}",
                flush=True,
            )
            _render_one(
                mujoco=mujoco,
                imageio=imageio,
                model=model,
                render_w=render_w,
                render_h=render_h,
                q_traj=q_traj,
                out_path=out_path,
                fps=int(args.fps),
                stride=int(args.stride),
            )
            ok += 1
        except Exception as e:
            fail += 1
            print(f"[ERROR] {traj_path}: {type(e).__name__}: {e}", flush=True)

    print(f"[BATCH DONE] success={ok} failed={fail}", flush=True)
    if ok == 0:
        raise RuntimeError("Batch rendering failed for all trajectories.")


if __name__ == "__main__":
    main()
