from __future__ import annotations

import json
from pathlib import Path

import numpy as np


def find_aligned_pose_jsons(session_dir: str | Path) -> list[Path]:
    """Find all demo pose files generated by AR_03_align_trajectory.py."""
    session_dir = Path(session_dir).expanduser().resolve()
    demos_dir = session_dir / "demos"
    if not demos_dir.is_dir():
        raise FileNotFoundError(f"Missing demos directory: {demos_dir}")
    files = sorted(demos_dir.glob("demo_*/aligned_arcap_poses.json"))
    return [x for x in files if x.is_file()]


def load_aligned_pose_json(json_path: str | Path) -> dict:
    """
    Load aligned_arcap_poses.json.

    Expected keys:
    - pose: list of [x,y,z,qx,qy,qz,qw]
    - timestamp: list of float
    - width: list of float
    """
    json_path = Path(json_path).expanduser().resolve()
    with open(json_path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    pose = np.asarray(raw.get("pose", []), dtype=np.float64)
    timestamp = np.asarray(raw.get("timestamp", []), dtype=np.float64)
    width = np.asarray(raw.get("width", []), dtype=np.float64)

    if pose.ndim != 2 or pose.shape[1] != 7:
        raise ValueError(f"{json_path}: pose shape must be (N,7), got {pose.shape}")
    n = pose.shape[0]
    if timestamp.shape[0] != n:
        raise ValueError(f"{json_path}: timestamp length {timestamp.shape[0]} != pose length {n}")
    if width.shape[0] != n:
        raise ValueError(f"{json_path}: width length {width.shape[0]} != pose length {n}")

    return {
        "path": json_path,
        "demo_name": json_path.parent.name,
        "pose": pose,
        "timestamp": timestamp,
        "width": width,
        "coordinate_frame": raw.get("coordinate_frame", "unknown"),
        "metadata": raw.get("metadata", {}),
    }

